defaultpages:
  manifest:
    path: manifest
    output: webmanifest
  serviceworker:
    path: serviceworker
    layout: serviceworker
    output: js
manifest:
  background_color: '#ffffff'
  theme_color: '#202020'
  icons:
    - src: icon-512x512.png
      sizes: 512x512
      type: image/png
serviceworker:
  enabled: false
