pages:
  default:
    manifest:
      path: manifest
      output: webmanifest
    serviceworker:
      path: serviceworker
      layout: serviceworker
      output: js
      multilingual: false
      serviceworker:
        precache: false
    offline:
      path: offline
      layout: offline
      output: html
      uglyurl: true
manifest:
  background_color: '#FFFFFF'
  theme_color: '#202020'
  icons:
    - icon-192x192.png
    #- icon-512x512.png
    #- src: icon-192x192-maskable.png
    #  purpose: maskable
    #- src: icon-512x512-maskable.png
    #  purpose: maskable
  shortcuts: false
  #screenshots:
  #  - screenshots/desktop.png
  #  - screenshots/mobile.png
serviceworker:
  enabled: false
  install:
    prompt: true # show install prompt
    precache:
      #assets:
      #  - images/example.png # relative path
      pages:
        limit: false # number or false
  cache:
    request: reload # 'reload' or 'default'
  update:
    snackbar:
      enabled: false # show Snackbar message
    badge:
      enabled: false # set badge on the icon
    notification:
      enabled: false # show notification
  offline:
    page: offline # offline page ID
    snackbar:
      enabled: false # show Snackbar message
