defaultpages:
  manifest:
    path: manifest
    output: webmanifest
  serviceworker:
    path: serviceworker
    layout: serviceworker
    output: js
manifest:
  background_color: '#FFFFFF'
  theme_color: '#202020'
  icons:
    - src: icon-192x192.png
      sizes: 192x192
      type: image/png
    - src: icon-512x512.png
      sizes: 512x512
      type: image/png
serviceworker:
  enabled: false
  notification:
    enabled: false
    message: 'New version'
