defaultpages:
  manifest:
    path: manifest
    output: webmanifest
  sw:
    path: serviceworker
    layout: serviceworker
    output: js
manifest:
  lang: en
  start_url: /
  display: standalone
  orientation: portrait
  background_color: '#ffffff'
  theme_color: '#202020'
serviceworker:
  enabled: false
  file: serviceworker.js
